 pool:
   vmImage: ubuntu-latest

 jobs:  
 - job: build
   displayName: 'Build'
   steps:
   - task: Maven@3
     inputs:
       mavenPomFile: 'pom.xml'
       publishJUnitResults: true
       allowBrokenSymlinks: 
       testResultsFiles: '**/TEST-*.xml'
       javaHomeOption: 'JDKVersion'
       sonarQubeRunAnalysis: false           

  
- job: sonar
  workspace:
    clean: all
    displayName:  Code Review
    steps:
  
  - task: SonarCloudPrepare@1
     inputs:
       SonarCloud: 'tarea4-devsecops'
       organization: 'rboblanco'
       projectKey: 'rboblanco_spring-boot-kubernetes'
       projectName: 'rboblanco'
       displayName: 'Preparing Sonarqube Environment'
      
      
   - task: Maven@3
     inputs:
       mavenPomFile: 'pom.xml'
       publishJUnitResults: true
       testResultsFiles: '**/surefire-reports/TEST-*.xml'
       javaHomeOption: 'JDKVersion'
       MavenVersionOption: 'Default'
       MavenAuthenticateFeed: false
       effetivePomSkip: false
       sonarQubeRunAnalysis: true
       sqMavenpluginVersionChoice:'lastest' 
         
   - task: SonarCloudPublish@1
     inputs:
       pollingTimeoutSec: '300'
       displayName: 'Publish Analysis Results'
    
  #- task: sonarcloud-buildbreaker@2
  #  inputs:
  #    SonarCloud: 'Sonarcloud'
  #    organization: 'devsecops-usach'
  
   job: sca
    steps:
   - task: dependency-check-build-task@6
     inputs:
       projectName: 'Talleres4-5'
       scanPath: '$(Pipeline.Workspace)'
       format: 'HTML'
       displayName: SCA
       
